# Generated by Django 2.1.3 on 2018-11-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20181129_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Имя услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Цена (BYN)'),
        ),
    ]
