# Generated by Django 2.1.3 on 2018-11-29 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='clientservices',
            options={'verbose_name': 'услуга клиента', 'verbose_name_plural': 'услуги клиента'},
        ),
        migrations.AddField(
            model_name='client',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
