# Generated by Django 2.1.3 on 2018-11-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20181129_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='clientservices',
            name='number_of_remaining_visits',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество оставшихся визитов'),
        ),
    ]
