# Generated by Django 2.1.3 on 2018-11-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20181129_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservices',
            name='service_debt',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Долг по услуге'),
        ),
        migrations.AlterField(
            model_name='clientservices',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='clientservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Услуга'),
        ),
    ]
